name: CI-brancher

on: pull_request

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'Mona the Octocat'

    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
  
    - uses: actions/checkout@v1
    
    - name: Run a multi-line script
      run: |
        set -x
        echo Add other actions to build,
        echo test, and deploy your project.
        env
        ls -la
        git status || true
        cat $GITHUB_EVENT_PATH | python -m json.tool
    
    - name: Create branch based on PR
      run: |
        set -x
        PR_NUM=$(echo $GITHUB_REF | cut -d / -f 3)
        BRANCH_NAME="${GITHUB_ACTOR}/pr${PR_NUM}-${GITHUB_HEAD_REF}"
        git checkout -B $BRANCH_NAME
        git push origin $BRANCH_NAME
        git branch -a -v
        
        
        
