name: CI-brancher

on: pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      
    - name: pr-brancher
      uses: submariner-io/pr-brancher@v1
      with:
        ssh-key: "${{ secrets.GIT_DEPLOY_KEY }}"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
